name: Nix build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Cachix build
      uses: cachix/cachix-action@v14
      with:
        # Name of a cachix cache to push and pull/substitute
        name: goffrie
        # Signing key secret retrieved after creating binary cache on https://cachix.org
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build build.nix
